ALTER TABLE tasks
  MODIFY COLUMN date DATE NULL,
  MODIFY COLUMN urgent BOOLEAN NULL DEFAULT NULL,
  ADD COLUMN due_date DATE NULL,
  ADD COLUMN important BOOLEAN NULL DEFAULT NULL,
  ADD COLUMN checklist JSON NOT NULL DEFAULT (JSON_ARRAY());
UPDATE tasks SET important = TRUE WHERE priority = 'high';
